### ISSUE TITLE
Best practices for backup verification and restore of data?

### ISSUE THREAD

**Issue by cro** [oetiker/znapzend#257]
Greetings,

Is there any best practice documentation for Znapzend regarding restoring data or verifying backups?

--cro

**Comment by hadfl** [comment]
verifying backups:
- filesets: there is a hidden directory in each fileset `.zfs/snapshot/<snap_name>/` where you could parse all files on source and destination, generate and compare checksums

- zvols: i think you'll have to clone the snapshot since you cannot access a zvol snapshot afaik. so clone the snapshot and then pipe `dd if=/dev/zvol/dsk/<clone_name>` to a checksumming program on source and destination and compare checksums. then destroy the clones.

restoring data:
just do a send/recv from the backup host to the source host. check zfs properties after restoring.

**Comment by cro** [comment]
Oh! You mean REALLY hidden.  It doesn't show up on any `ls`!  This makes much more sense now.
