### ISSUE TITLE
Weird "zfs destroy" behaviour

### ISSUE THREAD

**Issue by felibb** [oetiker/znapzend#325]
I have a simple pool with a single dataset, and a single manual znapzend snapshot. When running znapzend manually it does ```zfs destroy``` in a way I don't really understand. Examples below:

```
# zfs list -t all
NAME                          USED  AVAIL  REFER  MOUNTPOINT
tank                         1.00G  6.69G    24K  /tank
tank@2018-03-07-220617          0B      -    24K  -
tank/home                    1.00G  6.69G  1.00G  /tank/home
tank/home@2018-03-07-220617     0B      -  1.00G  -

===

# znapzend --debug --runonce=tank

# zfs list -t all
NAME                          USED  AVAIL  REFER  MOUNTPOINT
tank                         1.00G  6.69G    24K  /tank
tank@2018-03-07-220617          0B      -    24K  -
tank@2018-03-07-220708          0B      -    24K  -
tank/home                    1.00G  6.69G  1.00G  /tank/home
tank/home@2018-03-07-220617     0B      -  1.00G  -
tank/home@2018-03-07-220708     0B      -  1.00G  -

===

# znapzend --debug --runonce=tank

<output omitted>
# zfs list -H -o name -t snapshot -s creation -d 1 tank
[Wed Mar  7 22:07:46 2018] [debug] cleaning up snapshots on tank
# zfs destroy tank@2018-03-07-220708
# zfs list -H -o name -t snapshot -s creation -d 1 tank/home
[Wed Mar  7 22:07:46 2018] [debug] cleaning up snapshots on tank/home
# zfs destroy tank/home@2018-03-07-220708
<output omitted>

# zfs list -t all
NAME                          USED  AVAIL  REFER  MOUNTPOINT
tank                         1.00G  6.69G    24K  /tank
tank@2018-03-07-220617          0B      -    24K  -
tank@2018-03-07-220741          0B      -    24K  -
tank/home                    1.00G  6.69G  1.00G  /tank/home
tank/home@2018-03-07-220617     0B      -  1.00G  -
tank/home@2018-03-07-220741     0B      -  1.00G  -
```

Again:

```
# znapzend --debug --runonce=tank

<output omitted>
# zfs list -H -o name -t snapshot -s creation -d 1 tank
[Wed Mar  7 22:08:11 2018] [debug] cleaning up snapshots on tank
# zfs destroy tank@2018-03-07-220741
# zfs list -H -o name -t snapshot -s creation -d 1 tank/home
[Wed Mar  7 22:08:11 2018] [debug] cleaning up snapshots on tank/home
# zfs destroy tank/home@2018-03-07-220741
<output omitted>

# zfs list -t all
NAME                          USED  AVAIL  REFER  MOUNTPOINT
tank                         1.00G  6.69G    24K  /tank
tank@2018-03-07-220617          0B      -    24K  -
tank@2018-03-07-220805          0B      -    24K  -
tank/home                    1.00G  6.69G  1.00G  /tank/home
tank/home@2018-03-07-220617     0B      -  1.00G  -
tank/home@2018-03-07-220805     0B      -  1.00G  -
```

Here is the plan (in reality dst_0 is a tested and working host):

```
# znapzendzetup list
*** backup plan: tank ***
dst_0           = example.com:pool/test
dst_0_plan      = 2hours=>15minutes
enabled         = on
mbuffer         = /usr/bin/mbuffer
mbuffer_size    = 128M
post_znap_cmd   = off
pre_znap_cmd    = off
recursive       = on
src             = tank
src_plan        = 2hours=>15minutes
tsformat        = %Y-%m-%d-%H%M%S
zend_delay      = 0
```

So it destroys the most recent snapshot (which cannot be explained by the plan). It reproduces every time too. The DST snapshots are destroyed as well, I omitted it for simplicity's sake.

Why does this happen? Is this behaviour by design, or is it a bug?

Version (.deb from https://github.com/Gregy/znapzend-debian/releases/tag/v0.17.0-2):
```
# apt-cache policy znapzend
znapzend:
  Installed: 0.17.0-1
  Candidate: 0.17.0-1
  Version table:
 *** 0.17.0-1 100
        100 /var/lib/dpkg/status
```

OS:
```
# uname -a
Linux debian9 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
```

**Comment by lotheac** [comment]
I went over this with @felibb and I think we understand the behavior now:
https://github.com/oetiker/znapzend/blob/master/lib/ZnapZend/Time.pm#L184 tells us that the snapshots are kept in "time slots", in this case the shortest of which is 15 minutes. But we're running `--runonce` more than once per time slot, and znapzend wants to keep only one snapshot per time slot. So on the second run, it creates the snapshot 220708, and goes through the cleanup logic: at this point it would normally destroy 220708, because for this time slot it already had a prior snapshot 220617. But the latest snapshot is special-cased and never destroyed, so we end up with two snapshots occupying the same slot. However on the third run in the same slot, the cleanup code considers both 220708 and the just-created 220741 for destruction -- the latter is not destroyed because it is the latest, but the "middle" one 220708 does since this time slot already contains 220617.

It is a little strange to see this behavior though -- indeed we had to read the code to understand it :) I'm not sure how it could be improved -- arguably it could be a bug that we can end up with two snaps in the same timeslot, but then again it doesn't make sense to destroy the snap we've just created. We thought maybe it should always keep the latest snapshot from the timeslot, but then your 15min history could end up containing snaps for 15:14 and 15:15, not 15:00 and 15:15, so I don't really know.

But, well, this problem mostly only concerns `--runonce` - if we get multiple snaps in the same timeslot by other means (eg. changing the schedule) the situation corrects itself on the next timeslot (by destroying the extras).

**Comment by oetiker** [comment]
as a principle we try to err on the side of caution when it comes to deleting snapshots ...

**Comment by lotheac** [comment]
On Thu, Mar 08 2018 04:45:02 -0800, Tobias Oetiker wrote:
> as a principle we try to err on the side of caution when it comes to deleting snapshots ... 

which is why we initially started investigating this strange behavior
where it would appear to remove a snapshot without cause :)

-- 
Lauri Tirkkonen | lotheac @ IRCnet
