### ISSUE TITLE
zfs send via netcat or something similar fast?

### ISSUE THREAD

**Issue by utoedter** [oetiker/znapzend#351]
Hello,

It is possible to use for transferring the snapshots to destination another mechanism like netcat or rsh ? ssh eats up alot of cpu time.

**Comment by oetiker** [comment]
mbuffer can talik directly to the mbuffer on the other side!

**Comment by stuckj** [comment]
In case anyone, like me, didn't know how to do this. Look in the znapzendzetup docs (https://github.com/oetiker/znapzend/blob/master/doc/znapzendzetup.pod). Specifically, at this part:

```
--mbuffer=/usr/bin/mbuffer:31337
Specify the path to your copy of the mbuffer utility and the port used on the destination. Caution: znapzend will send the data directly from source mbuffer to destination mbuffer, thus data stream is not encrypted.
```

You need to make sure to use a different port for each dataset that's going to do this though so they don't step on each other if run in parallel since the destination can only have one buffer instance listening per port. I achieved this in a script that sets up all my datasets by just using a PORT variable initialized to a value and using $((PORT++)) as the port value in the mbuffer config each time (so it post-increments the value).
