### ISSUE TITLE
Autodetect --features=compressed if SRC and DST are compressed

### ISSUE THREAD

**Issue by Harvie** [oetiker/znapzend#424]
I think that --features=compressed should be enabled by default if both pools are compressed.
Maybe it's enough to check if DST is compressed, because if SRC is not compressed, `-c` will not work anyway...

**Comment by jimklimov** [comment]
I think it *can* be more difficult than that, because depending on zpool and zfs versions/format/features/(vendors)/... the sender and receiver might not have an agreeable compressed-data protocol, which is something an admin who sets stuff up can/should know, although scripts might test for (try to send a test blurb and compare the result, see if it errors out) but it may be impractical (delay, storage write-wear, ...) for doing upon every send or service startup.

**Comment by Harvie** [comment]
bump
