### ISSUE TITLE
error handling of no existing dataset

### ISSUE THREAD

**Issue by moetiker** [oetiker/znapzend#539]
```
znapzendzetup edit ssd-a/home-a
cannot open 'ssd-a/home-a': dataset does not exist
Can't use string ("0") as an ARRAY ref while "strict refs" in use at /opt/ooce/bin/znapzendzetup line 236.
```

**Comment by yggdr** [comment]
I just started out with znapzend and am running into the same issue. Do I really have to create all the recursive datasets on each backup destination by hand? That seems just wrong.

Example:
*** backup plan: storage ***
dst_nas = primarybackup:master/backup/midgard/storage

`storage` locally has several subdatasets, and sending fails because `cannot open 'master/backup/midgard/storage/arbeit': dataset does not exist`
