### ISSUE TITLE
Noob needs help with command syntax

### ISSUE THREAD

**Issue by wallart1** [oetiker/znapzend#668]
I'm attempting my first actual command with znapzend, but I don't see the error in my command. Please help me out. 

```
root@foghorn:/# znapzendzetup create \
    --tsformat="znapzend-%Y%m%d-%H%M%S" \
    --recursive \ 
    SRC "36hour=>12hour,3day=>1day,1week=>2week,2month=>1month" fivebays/virtualboxbackup/main/XMR \
        DST:a "2month=>1month" \
            z22tb/virtualboxoffsite/main/XMR
ERROR: don't know what to do with  . check the syntax

SRC: command not found
root@foghorn:/# znapzend --version
znapzend version 0.dev
root@foghorn:/# apt list znapzend
Listing... Done
znapzend/now 0.23.2 amd64 [installed,local]
root@foghorn:/# 
```
I used the .deb release from this repository. Running on Linux Mint Cinnamon Edition 21.3.

Thanks.

PS: I've corrected the "1week=>2week" to "2week=>1week".

**Comment by hadfl** [comment]
`SRC: command not found` incicates that the line starting with `SRC` was run by the shell as a separate command and not as additional parameters to your initial `znapzendzetup` command.

This is likely due to trailing character(s) (e.g. a space) after the escape in the line before. Which will then lead to that character being escaped instead of the newline character.

**Comment by wallart1** [comment]
That was the problem. Thanks so much for your insight. And thank you for writing this system and making it available to everyone.
